-- Schéma initial complet. Flyway est désormais l'unique propriétaire du schéma :
-- toute base neuve (poste de développement, préproduction, production) est créée
-- par cette migration, et non plus par la génération automatique d'Hibernate.
--
-- Le contenu reflète le modèle JPA courant. Les profils applicatifs utilisent
-- ddl-auto=validate : Hibernate vérifie l'accord entre entités et schéma sans
-- jamais le modifier.

-- ===============================
-- Référentiels indépendants
-- ===============================

CREATE TABLE doyenne (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id   UUID          NOT NULL UNIQUE,
    nom         VARCHAR(400)  NOT NULL,
    description VARCHAR(500),
    status_del  BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6)
);

CREATE TABLE users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id  UUID         NOT NULL UNIQUE,
    nom        VARCHAR(100) NOT NULL,
    prenom     VARCHAR(150) NOT NULL,
    username   VARCHAR(100) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    email      VARCHAR(150),
    telephone  VARCHAR(50),
    role       VARCHAR(32)  NOT NULL,
    is_global  BOOLEAN      NOT NULL DEFAULT FALSE,
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    status_del BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT ck_users_role
        CHECK (role IN ('SECRETAIRE', 'CURE', 'ADMIN', 'COMPTABLE', 'SUPER_ADMIN'))
);

CREATE TABLE type_paiement (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id  UUID         NOT NULL UNIQUE,
    libelle    VARCHAR(255) NOT NULL,
    mode       VARCHAR(255) NOT NULL,
    status_del BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT ck_type_paiement_mode
        CHECK (mode IN ('TMONEY', 'FLOOZ', 'ESPECES', 'CARTE'))
);

-- ===============================
-- Paroisse : le tenant fonctionnel
-- ===============================

CREATE TABLE paroisse (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               UUID         NOT NULL UNIQUE,
    nom                     VARCHAR(100) NOT NULL,
    adresse                 VARCHAR(200) NOT NULL,
    email                   VARCHAR(150),
    telephone               VARCHAR(50),
    doyenne_id              BIGINT       NOT NULL,
    nom_banque              VARCHAR(120),
    titulaire_compte        VARCHAR(150),
    iban_or_rib             VARCHAR(80),
    subscription_expires_at TIMESTAMP(6),
    is_active               BOOLEAN      NOT NULL DEFAULT TRUE,
    status_del              BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP(6),
    updated_at              TIMESTAMP(6),
    CONSTRAINT fk_paroisse_doyenne FOREIGN KEY (doyenne_id) REFERENCES doyenne (id)
);

CREATE TABLE paroisse_access (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID        NOT NULL UNIQUE,
    user_id       BIGINT      NOT NULL,
    paroisse_id   BIGINT      NOT NULL,
    role_paroisse VARCHAR(50) NOT NULL,
    active        BOOLEAN     NOT NULL DEFAULT TRUE,
    status_del    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP(6),
    updated_at    TIMESTAMP(6),
    CONSTRAINT fk_paroisse_access_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_paroisse_access_paroisse FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT ck_paroisse_access_role
        CHECK (role_paroisse IN ('ADMIN', 'GESTIONNAIRE', 'SECRETAIRE', 'CONSULTATION'))
);

CREATE TABLE horaire (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL UNIQUE,
    paroisse_id       BIGINT       NOT NULL,
    jour_semaine      VARCHAR(255) NOT NULL,
    heure_celebration TIME(6)      NOT NULL,
    libelle           VARCHAR(150),
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    status_del        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP(6),
    updated_at        TIMESTAMP(6),
    CONSTRAINT fk_horaire_paroisse FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT ck_horaire_jour_semaine
        CHECK (jour_semaine IN ('DIMANCHE', 'LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI'))
);

-- ===============================
-- Catalogue métier
-- ===============================

CREATE TABLE type_demande (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id            UUID         NOT NULL UNIQUE,
    paroisse_id          BIGINT       NOT NULL,
    type_principal       VARCHAR(50)  NOT NULL,
    libelle              VARCHAR(150) NOT NULL,
    description          VARCHAR(255),
    delai_minimum_heures INTEGER      NOT NULL DEFAULT 24,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    status_del           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP(6),
    updated_at           TIMESTAMP(6),
    CONSTRAINT fk_type_demande_paroisse FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT uk_type_demande_libelle_paroisse_type UNIQUE (libelle, paroisse_id, type_principal),
    CONSTRAINT ck_type_demande_type_principal
        CHECK (type_principal IN ('EUCHARISTIE', 'SACRAMENT', 'SACRAMENTAUX'))
);

CREATE TABLE type_demande_jour_autorise (
    type_demande_id BIGINT      NOT NULL,
    jour_semaine    VARCHAR(20) NOT NULL,
    PRIMARY KEY (type_demande_id, jour_semaine),
    CONSTRAINT fk_type_demande_jour_type_demande
        FOREIGN KEY (type_demande_id) REFERENCES type_demande (id),
    CONSTRAINT ck_type_demande_jour_semaine
        CHECK (jour_semaine IN ('DIMANCHE', 'LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI'))
);

CREATE TABLE forfait_tarif (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID           NOT NULL UNIQUE,
    type_demande_id    BIGINT         NOT NULL,
    code_forfait       VARCHAR(50)    NOT NULL UNIQUE,
    nom_forfait        VARCHAR(150)   NOT NULL,
    nature_forfait     VARCHAR(20)    NOT NULL,
    libelle            VARCHAR(255),
    montant_forfait    NUMERIC(12, 2) NOT NULL,
    nombre_celebration INTEGER,
    nombre_jour        INTEGER,
    heure_personnalise BOOLEAN        NOT NULL DEFAULT FALSE,
    is_active          BOOLEAN        NOT NULL DEFAULT TRUE,
    status_del         BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP(6),
    updated_at         TIMESTAMP(6),
    CONSTRAINT fk_forfait_tarif_type_demande
        FOREIGN KEY (type_demande_id) REFERENCES type_demande (id),
    CONSTRAINT uk_forfait_tarif_nom_type_demande UNIQUE (nom_forfait, type_demande_id),
    CONSTRAINT ck_forfait_tarif_nature
        CHECK (nature_forfait IN ('NORMALE', 'DOMINICALE', 'SPECIALE'))
);

CREATE TABLE forfait_tarif_jour_autorise (
    forfait_tarif_id BIGINT      NOT NULL,
    jour_semaine     VARCHAR(20) NOT NULL,
    PRIMARY KEY (forfait_tarif_id, jour_semaine),
    CONSTRAINT fk_forfait_tarif_jour_forfait
        FOREIGN KEY (forfait_tarif_id) REFERENCES forfait_tarif (id),
    CONSTRAINT ck_forfait_tarif_jour_semaine
        CHECK (jour_semaine IN ('DIMANCHE', 'LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI'))
);

-- ===============================
-- Demandes et facturation
-- ===============================

CREATE TABLE demande (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID           NOT NULL UNIQUE,
    code_suivie        VARCHAR(100)   NOT NULL UNIQUE,
    paroisse_id        BIGINT         NOT NULL,
    type_demande_id    BIGINT         NOT NULL,
    forfait_tarif_id   BIGINT         NOT NULL,
    horaire_id         BIGINT,
    type_paiement_id   BIGINT,
    user_id            BIGINT,
    nom_fidele         VARCHAR(100)   NOT NULL,
    prenom_fidele      VARCHAR(100)   NOT NULL,
    tel_fidele         VARCHAR(30)    NOT NULL,
    email_fidele       VARCHAR(150),
    intention          VARCHAR(500)   NOT NULL,
    montant            NUMERIC(12, 2) NOT NULL,
    heure_personnalisee TIME(6),
    nom_coursier       VARCHAR(100),
    validate_by        VARCHAR(150),
    statut_demande     VARCHAR(30)    NOT NULL,
    statut_paiement    VARCHAR(30)    NOT NULL,
    statut_validation  VARCHAR(30)    NOT NULL,
    status_del         BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP(6),
    updated_at         TIMESTAMP(6),
    CONSTRAINT fk_demande_paroisse FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT fk_demande_type_demande FOREIGN KEY (type_demande_id) REFERENCES type_demande (id),
    CONSTRAINT fk_demande_forfait_tarif FOREIGN KEY (forfait_tarif_id) REFERENCES forfait_tarif (id),
    CONSTRAINT fk_demande_horaire FOREIGN KEY (horaire_id) REFERENCES horaire (id),
    CONSTRAINT fk_demande_type_paiement FOREIGN KEY (type_paiement_id) REFERENCES type_paiement (id),
    CONSTRAINT fk_demande_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_demande_statut_demande
        CHECK (statut_demande IN ('EN_ATTENTE', 'VALIDEE', 'REJETEE', 'ANNULEE', 'TERMINEE')),
    CONSTRAINT ck_demande_statut_paiement
        CHECK (statut_paiement IN ('NON_PAYE', 'EN_ATTENTE', 'PAYE', 'ECHOUE')),
    CONSTRAINT ck_demande_statut_validation
        CHECK (statut_validation IN ('EN_ATTENTE', 'VALIDEE', 'REJETEE'))
);

CREATE TABLE demande_date (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID    NOT NULL UNIQUE,
    demande_id       BIGINT  NOT NULL,
    date_celebration DATE    NOT NULL,
    ordre            INTEGER NOT NULL,
    status_del       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    CONSTRAINT fk_demande_date_demande FOREIGN KEY (demande_id) REFERENCES demande (id),
    CONSTRAINT uk_demande_date_demande_date UNIQUE (demande_id, date_celebration),
    CONSTRAINT uk_demande_date_demande_ordre UNIQUE (demande_id, ordre)
);

CREATE TABLE facture (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL UNIQUE,
    demande_id      BIGINT       NOT NULL UNIQUE,
    ref_facture     VARCHAR(100) NOT NULL UNIQUE,
    montant         INTEGER      NOT NULL,
    statut_paiement VARCHAR(255) NOT NULL,
    date_paiement   TIMESTAMP(6),
    status_del      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT fk_facture_demande FOREIGN KEY (demande_id) REFERENCES demande (id),
    CONSTRAINT ck_facture_statut_paiement
        CHECK (statut_paiement IN ('NON_PAYE', 'EN_ATTENTE', 'PAYE', 'ECHOUE'))
);

CREATE TABLE details_paiement (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                UUID         NOT NULL UNIQUE,
    facture_id               BIGINT       NOT NULL UNIQUE,
    type_paiement_id         BIGINT       NOT NULL,
    montant                  INTEGER      NOT NULL,
    montant_frais            INTEGER      NOT NULL DEFAULT 0,
    montant_frais_agregateur INTEGER      NOT NULL DEFAULT 0,
    montant_frais_plateforme INTEGER      NOT NULL DEFAULT 0,
    montant_charge           INTEGER,
    montant_net              INTEGER,
    numero                   VARCHAR(30),
    provider                 VARCHAR(40),
    id_transaction           VARCHAR(150),
    payment_url              VARCHAR(500),
    statut_paiement          VARCHAR(255) NOT NULL,
    date_details_paiement    TIMESTAMP(6) NOT NULL,
    status_del               BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMP(6),
    updated_at               TIMESTAMP(6),
    CONSTRAINT fk_details_paiement_facture FOREIGN KEY (facture_id) REFERENCES facture (id),
    CONSTRAINT fk_details_paiement_type_paiement FOREIGN KEY (type_paiement_id) REFERENCES type_paiement (id),
    CONSTRAINT ck_details_paiement_statut
        CHECK (statut_paiement IN ('NON_PAYE', 'EN_ATTENTE', 'PAYE', 'ECHOUE'))
);

-- ===============================
-- Plateforme : inscription, abonnement, comptabilité
-- ===============================

CREATE TABLE paroisse_inscription (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID         NOT NULL UNIQUE,
    nom_paroisse        VARCHAR(100) NOT NULL,
    adresse             VARCHAR(200) NOT NULL,
    email               VARCHAR(150),
    telephone           VARCHAR(50),
    doyenne_public_id   UUID         NOT NULL,
    plan_abonnement     VARCHAR(30)  NOT NULL,
    admin_nom           VARCHAR(80)  NOT NULL,
    admin_prenom        VARCHAR(80)  NOT NULL,
    admin_email         VARCHAR(150) NOT NULL,
    admin_telephone     VARCHAR(50),
    admin_username      VARCHAR(80)  NOT NULL,
    admin_password_hash VARCHAR(255) NOT NULL,
    statut              VARCHAR(30)  NOT NULL,
    message             VARCHAR(500),
    paroisse_public_id  UUID,
    status_del          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6),
    CONSTRAINT ck_paroisse_inscription_plan
        CHECK (plan_abonnement IN ('MENSUEL', 'SEMESTRIEL', 'ANNUEL')),
    CONSTRAINT ck_paroisse_inscription_statut
        CHECK (statut IN ('SOUMISE', 'APPROUVEE', 'REJETEE'))
);

CREATE TABLE paroisse_inscription_membre (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscription_id BIGINT      NOT NULL,
    nom            VARCHAR(80) NOT NULL,
    prenom         VARCHAR(80) NOT NULL,
    email          VARCHAR(150),
    telephone      VARCHAR(50),
    role_paroisse  VARCHAR(40) NOT NULL,
    username       VARCHAR(80),
    CONSTRAINT fk_inscription_membre_inscription
        FOREIGN KEY (inscription_id) REFERENCES paroisse_inscription (id),
    CONSTRAINT ck_inscription_membre_role
        CHECK (role_paroisse IN ('ADMIN', 'GESTIONNAIRE', 'SECRETAIRE', 'CONSULTATION'))
);

CREATE TABLE paroisse_abonnement (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id      UUID        NOT NULL UNIQUE,
    paroisse_id    BIGINT      NOT NULL,
    plan           VARCHAR(30) NOT NULL,
    montant        INTEGER     NOT NULL,
    debut_at       TIMESTAMP(6),
    fin_at         TIMESTAMP(6),
    statut         VARCHAR(30) NOT NULL,
    id_transaction VARCHAR(150),
    payment_url    VARCHAR(500),
    status_del     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP(6),
    updated_at     TIMESTAMP(6),
    CONSTRAINT fk_abonnement_paroisse FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT ck_abonnement_plan
        CHECK (plan IN ('MENSUEL', 'SEMESTRIEL', 'ANNUEL')),
    CONSTRAINT ck_abonnement_statut
        CHECK (statut IN ('EN_ATTENTE', 'ACTIF', 'EXPIRE', 'ANNULE'))
);

CREATE TABLE compte_paroisse (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id        UUID    NOT NULL UNIQUE,
    paroisse_id      BIGINT  NOT NULL UNIQUE,
    solde_disponible INTEGER NOT NULL DEFAULT 0,
    solde_en_attente INTEGER NOT NULL DEFAULT 0,
    status_del       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    CONSTRAINT fk_compte_paroisse_paroisse FOREIGN KEY (paroisse_id) REFERENCES paroisse (id)
);

CREATE TABLE ecriture_comptable (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id           UUID         NOT NULL UNIQUE,
    paroisse_id         BIGINT       NOT NULL,
    type_ecriture       VARCHAR(40)  NOT NULL,
    montant             INTEGER      NOT NULL,
    libelle             VARCHAR(255) NOT NULL,
    reference_externe   VARCHAR(150),
    demande_code_suivie VARCHAR(80),
    status_del          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6),
    CONSTRAINT fk_ecriture_paroisse FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT ck_ecriture_type
        CHECK (type_ecriture IN ('CREDIT_MESSE', 'DEBIT_REVERSEMENT', 'DEBIT_REVERSEMENT_HOLD',
                                 'CREDIT_REVERSEMENT_REJECT', 'AJUSTEMENT'))
);

CREATE TABLE demande_reversement (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id          UUID        NOT NULL UNIQUE,
    paroisse_id        BIGINT      NOT NULL,
    montant            INTEGER     NOT NULL,
    statut             VARCHAR(30) NOT NULL,
    nom_banque         VARCHAR(120),
    titulaire_compte   VARCHAR(150),
    iban_or_rib        VARCHAR(80),
    motif              VARCHAR(500),
    reference_virement VARCHAR(120),
    traite_par         VARCHAR(120),
    traite_at          TIMESTAMP(6),
    status_del         BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP(6),
    updated_at         TIMESTAMP(6),
    CONSTRAINT fk_reversement_paroisse FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT ck_reversement_statut
        CHECK (statut IN ('EN_ATTENTE', 'PAYE', 'REJETE'))
);
