CREATE TABLE annee_pastorale (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id    UUID          NOT NULL UNIQUE,
    paroisse_id  BIGINT        NOT NULL,
    libelle      VARCHAR(100)  NOT NULL,
    date_debut   DATE          NOT NULL,
    date_fin     DATE          NOT NULL,
    description  VARCHAR(1000),
    statut       VARCHAR(20)   NOT NULL DEFAULT 'BROUILLON',
    published_at TIMESTAMP(6),
    closed_at    TIMESTAMP(6),
    version      BIGINT        NOT NULL DEFAULT 0,
    status_del   BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    CONSTRAINT fk_annee_pastorale_paroisse
        FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT ck_annee_pastorale_dates
        CHECK (date_fin > date_debut),
    CONSTRAINT ck_annee_pastorale_statut
        CHECK (statut IN ('BROUILLON', 'PUBLIEE', 'CLOTUREE')),
    CONSTRAINT ck_annee_pastorale_lifecycle_dates
        CHECK (
            (statut = 'BROUILLON' AND published_at IS NULL AND closed_at IS NULL)
            OR (statut = 'PUBLIEE' AND published_at IS NOT NULL AND closed_at IS NULL)
            OR (statut = 'CLOTUREE' AND published_at IS NOT NULL AND closed_at IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_annee_pastorale_libelle_paroisse
    ON annee_pastorale (paroisse_id, LOWER(libelle))
    WHERE status_del = FALSE;

CREATE UNIQUE INDEX uq_annee_pastorale_publiee_paroisse
    ON annee_pastorale (paroisse_id)
    WHERE statut = 'PUBLIEE' AND status_del = FALSE;

CREATE INDEX idx_annee_pastorale_paroisse_dates
    ON annee_pastorale (paroisse_id, date_debut DESC, date_fin DESC)
    WHERE status_del = FALSE;

COMMENT ON TABLE annee_pastorale IS
    'Cadre temporel versionné des activités pastorales d''une paroisse.';
