CREATE TABLE acteur_pastoral (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id    UUID          NOT NULL UNIQUE,
    paroisse_id  BIGINT        NOT NULL,
    nom          VARCHAR(100)  NOT NULL,
    prenoms      VARCHAR(150)  NOT NULL,
    appellation  VARCHAR(50),
    categorie    VARCHAR(30)   NOT NULL,
    telephone    VARCHAR(50),
    email        VARCHAR(150),
    notes        VARCHAR(1000),
    actif        BOOLEAN       NOT NULL DEFAULT TRUE,
    version      BIGINT        NOT NULL DEFAULT 0,
    status_del   BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    CONSTRAINT fk_acteur_pastoral_paroisse
        FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT ck_acteur_pastoral_categorie
        CHECK (categorie IN ('CLERGE', 'VIE_CONSACREE', 'LAIC', 'AUTRE'))
);

CREATE INDEX idx_acteur_pastoral_paroisse_nom
    ON acteur_pastoral (paroisse_id, LOWER(nom), LOWER(prenoms))
    WHERE status_del = FALSE;

CREATE INDEX idx_acteur_pastoral_paroisse_actif
    ON acteur_pastoral (paroisse_id, actif)
    WHERE status_del = FALSE;

COMMENT ON TABLE acteur_pastoral IS
    'Répertoire paroissial des personnes pouvant recevoir un mandat ou une affectation pastorale.';
