CREATE TABLE structure_pastorale (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID          NOT NULL UNIQUE,
    paroisse_id     BIGINT        NOT NULL,
    type            VARCHAR(40)   NOT NULL,
    nom             VARCHAR(150)  NOT NULL,
    attributions    VARCHAR(1500),
    ordre_affichage INTEGER       NOT NULL DEFAULT 0,
    actif           BOOLEAN       NOT NULL DEFAULT TRUE,
    version         BIGINT        NOT NULL DEFAULT 0,
    status_del      BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT fk_structure_pastorale_paroisse
        FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT ck_structure_pastorale_type
        CHECK (type IN (
            'COMMUNAUTE_SACERDOTALE',
            'CPP',
            'CPAE',
            'COMMISSION',
            'GROUPE_CONSTITUE',
            'CHORALE',
            'ASSOCIATION_MOUVEMENT_ORDRE',
            'AUTRE'
        )),
    CONSTRAINT ck_structure_pastorale_ordre
        CHECK (ordre_affichage >= 0)
);

CREATE UNIQUE INDEX uq_structure_pastorale_nom_type
    ON structure_pastorale (paroisse_id, type, LOWER(nom))
    WHERE status_del = FALSE;

CREATE INDEX idx_structure_pastorale_paroisse_type
    ON structure_pastorale (paroisse_id, type, ordre_affichage, nom)
    WHERE status_del = FALSE;

CREATE TABLE mandat_pastoral (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id                UUID          NOT NULL UNIQUE,
    paroisse_id              BIGINT        NOT NULL,
    annee_pastorale_id       BIGINT        NOT NULL,
    acteur_pastoral_id       BIGINT        NOT NULL,
    structure_pastorale_id   BIGINT        NOT NULL,
    fonction                 VARCHAR(120)  NOT NULL,
    attributions             VARCHAR(1500),
    date_debut               DATE          NOT NULL,
    date_fin                 DATE          NOT NULL,
    ordre_affichage          INTEGER       NOT NULL DEFAULT 0,
    version                  BIGINT        NOT NULL DEFAULT 0,
    status_del               BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMP(6),
    updated_at               TIMESTAMP(6),
    CONSTRAINT fk_mandat_pastoral_paroisse
        FOREIGN KEY (paroisse_id) REFERENCES paroisse (id),
    CONSTRAINT fk_mandat_pastoral_annee
        FOREIGN KEY (annee_pastorale_id) REFERENCES annee_pastorale (id),
    CONSTRAINT fk_mandat_pastoral_acteur
        FOREIGN KEY (acteur_pastoral_id) REFERENCES acteur_pastoral (id),
    CONSTRAINT fk_mandat_pastoral_structure
        FOREIGN KEY (structure_pastorale_id) REFERENCES structure_pastorale (id),
    CONSTRAINT ck_mandat_pastoral_dates
        CHECK (date_fin >= date_debut),
    CONSTRAINT ck_mandat_pastoral_ordre
        CHECK (ordre_affichage >= 0)
);

CREATE INDEX idx_mandat_pastoral_annee_structure
    ON mandat_pastoral (
        paroisse_id,
        annee_pastorale_id,
        structure_pastorale_id,
        ordre_affichage
    )
    WHERE status_del = FALSE;

CREATE INDEX idx_mandat_pastoral_acteur
    ON mandat_pastoral (acteur_pastoral_id, date_debut, date_fin)
    WHERE status_del = FALSE;

COMMENT ON TABLE structure_pastorale IS
    'Instances et groupes de la paroisse : communauté sacerdotale, CPP, CPAE, commissions, chorales et mouvements.';

COMMENT ON TABLE mandat_pastoral IS
    'Fonction exercée par un acteur dans une structure pendant une année pastorale.';
