-- Annuaire de référence de l'Archidiocèse de Lomé : 13 doyennés et 134 paroisses.
-- Source : https://archidiocesedelome.tg/paroisses
--
-- Les paroisses sont créées inactives (is_active = false) : elles existent dans
-- l'annuaire mais ne deviennent des tenants exploitables qu'après souscription
-- et activation par le comptable plateforme.
--
-- L'adresse est obligatoire en base alors que la source ne publie que la
-- localité, contenue dans le suffixe du nom. Elle sert donc de valeur de départ,
-- à préciser par chaque paroisse lors de son inscription.
--
-- Les deux INSERT sont idempotents : ON CONFLICT DO NOTHING s'appuie sur les
-- index uniques partiels de V2, si bien qu'un doyenné ou une paroisse déjà saisi
-- à la main est conservé tel quel.

INSERT INTO doyenne (public_id, nom, description, status_del, created_at, updated_at)
SELECT gen_random_uuid(), src.nom, src.description, FALSE, LOCALTIMESTAMP, LOCALTIMESTAMP
FROM (VALUES
    ('Lomé-Centre',                'Doyenné I'),
    ('Lomé-Nord 1 (Hédzranawoé)',  'Doyenné II'),
    ('Lomé-Nord 2 (Tokoin)',       'Doyenné III'),
    ('Lomé-Est 1 (Bè)',            'Doyenné IV'),
    ('Lomé-Est 2 (Baguida)',       'Doyenné V'),
    ('Lomé-Ouest 1 (Klikamé)',     'Doyenné VI'),
    ('Lomé-Ouest 2 (Agoè-Nyivé)',  'Doyenné VII'),
    ('Lomé-Ouest 3 (Adidogomé)',   'Doyenné VIII'),
    ('Lomé-Ouest 4 (Sanguéra)',    'Doyenné IX'),
    ('Nord-Est 1 (Tsévié)',        'Doyenné X'),
    ('Nord-Est 2 (Agbélouvé)',     'Doyenné XI'),
    ('Nord-Est 3 (Abobo)',         'Doyenné XII'),
    ('Nord-Ouest (Assahoun)',      'Doyenné XIII')
) AS src(nom, description)
ON CONFLICT DO NOTHING;

-- La jointure est volontairement une LEFT JOIN : un doyenné mal orthographié
-- produirait un doyenne_id NULL et ferait échouer la migration au lieu de
-- perdre silencieusement des paroisses.
INSERT INTO paroisse (public_id, nom, adresse, doyenne_id, is_active, status_del, created_at, updated_at)
SELECT gen_random_uuid(), src.nom, src.adresse, dy.id, FALSE, FALSE, LOCALTIMESTAMP, LOCALTIMESTAMP
FROM (VALUES
    ('Communauté Anglophone / Foyer Pie XII', 'Foyer Pie XII', 'Lomé-Centre'),
    ('Communauté Chrétienne Marie Reine des Anges / Démé', 'Démé', 'Nord-Est 1 (Tsévié)'),
    ('Communauté Chrétienne Saint Esprit / Anyavé', 'Anyavé', 'Nord-Est 1 (Tsévié)'),
    ('Communauté Chrétienne Saint Jean Baptiste de La Salle / Cacaveli (SVD)', 'Cacaveli', 'Lomé-Ouest 1 (Klikamé)'),
    ('Communauté Chrétienne Saint Jean Paul II / Dikamé', 'Dikamé', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Communauté Chrétienne Saint Jean-Baptiste', 'Assahoun', 'Nord-Ouest (Assahoun)'),
    ('Communauté Chrétienne Saint Jean-Baptiste / Tedo-Ananissimé', 'Tedo-Ananissimé', 'Nord-Ouest (Assahoun)'),
    ('Communauté Chrétienne Saint Joseph Freinademetz / Alinka', 'Alinka', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Cathédrale Sacré-Cœur de Jésus', 'Lomé', 'Lomé-Centre'),
    ('Paroisse Christ Ressuscité / Sagbado-Logoté (OFM)', 'Sagbado-Logoté', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Christ-Roi / Adétikopé', 'Adétikopé', 'Nord-Est 1 (Tsévié)'),
    ('Paroisse Christ-Roi / Kodzoviakopé', 'Kodzoviakopé', 'Lomé-Centre'),
    ('Paroisse Cœur Immaculé de Marie / Téléssou', 'Téléssou', 'Lomé-Ouest 1 (Klikamé)'),
    ('Paroisse Corpus Christi / Cacaveli (SVD)', 'Cacaveli', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Cristo Risorto / Hédzranawoé', 'Hédzranawoé', 'Lomé-Nord 1 (Hédzranawoé)'),
    ('Paroisse Immaculée Conception / Aveta', 'Aveta', 'Nord-Est 3 (Abobo)'),
    ('Paroisse Immaculée Conception / Nyékonakpoè', 'Nyékonakpoè', 'Lomé-Centre'),
    ('Paroisse Immaculée Conception / Zogbépimé', 'Zogbépimé', 'Nord-Ouest (Assahoun)'),
    ('Paroisse Jésus Bon Pasteur / Agoè-Assiyéyé', 'Agoè-Assiyéyé', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Jésus Miséricordieux / Amadahomé', 'Amadahomé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Jésus Miséricordieux / Avépozo-Kpota (SMA)', 'Avépozo-Kpota', 'Lomé-Est 2 (Baguida)'),
    ('Paroisse Maria Auxiliadora / Gbényédzi (SDB)', 'Gbényédzi', 'Lomé-Est 1 (Bè)'),
    ('Paroisse Marie Mère du Rédempteur / Adidogomé (MCCJ)', 'Adidogomé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Marie Reine / Gapé-Akpakpédomé', 'Gapé-Akpakpédomé', 'Nord-Est 2 (Agbélouvé)'),
    ('Paroisse Marie Reine des Apôtres / Vakpossito', 'Vakpossito', 'Lomé-Ouest 1 (Klikamé)'),
    ('Paroisse Marie Reine du Monde / Bè-Apéyémé', 'Bè-Apéyémé', 'Lomé-Est 1 (Bè)'),
    ('Paroisse Marie Theotokos / Agoè-Nyivé (SVD)', 'Agoè-Nyivé', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Médaille Miraculeuse / Kohé', 'Kohé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Notre Dame de Fatima / Avédzi', 'Avédzi', 'Lomé-Ouest 1 (Klikamé)'),
    ('Paroisse Notre Dame de Guadalupe / Gapé-Atsanvé', 'Gapé-Atsanvé', 'Nord-Est 2 (Agbélouvé)'),
    ('Paroisse Notre Dame de Guadalupe / Sanyramé', 'Sanyramé', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Paroisse Notre Dame de l''Assomption / Agoè-Démakpoé-Apégnigbi', 'Agoè-Démakpoé-Apégnigbi', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Notre Dame de l''Assomption / Assahoun', 'Assahoun', 'Nord-Ouest (Assahoun)'),
    ('Paroisse Notre Dame de la Miséricorde / Agblégan', 'Agblégan', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Notre Dame de la Miséricorde / Anyron', 'Anyron', 'Nord-Ouest (Assahoun)'),
    ('Paroisse Notre Dame de la Miséricorde / Attiégou II', 'Attiégou II', 'Lomé-Nord 1 (Hédzranawoé)'),
    ('Paroisse Notre Dame de la Paix / Athiémé (Assomptionnistes)', 'Athiémé', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Paroisse Notre Dame de la Paix / Tokoin-Novissi', 'Tokoin-Novissi', 'Lomé-Nord 2 (Tokoin)'),
    ('Paroisse Notre Dame de la Paix / Zongo', 'Zongo', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Notre Dame de la Rédemption / Bè-Klikamé', 'Bè-Klikamé', 'Lomé-Ouest 1 (Klikamé)'),
    ('Paroisse Notre Dame de Lourdes / Bè-Adidomé', 'Bè-Adidomé', 'Lomé-Est 1 (Bè)'),
    ('Paroisse Notre Dame des Douleurs / Kpali-Dévé', 'Kpali-Dévé', 'Nord-Est 1 (Tsévié)'),
    ('Paroisse Notre Dame des Douleurs / Kpogamé-Apéyéyémé', 'Kpogamé-Apéyéyémé', 'Nord-Est 3 (Abobo)'),
    ('Paroisse Notre Dame du Liban (Rite Maronite)', 'Hédzranawoé', 'Lomé-Nord 1 (Hédzranawoé)'),
    ('Paroisse Notre Dame du Mont Carmel / Gbomamé', 'Gbomamé', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Paroisse Notre Dame du Perpétuel Secours / Agodéké-Kpogan (SMA)', 'Agodéké-Kpogan', 'Lomé-Est 2 (Baguida)'),
    ('Paroisse Notre Dame du Perpétuel Secours / Segbé', 'Segbé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Notre Dame du Perpétuel Secours / Zégle Yéyé', 'Zégle Yéyé', 'Nord-Est 3 (Abobo)'),
    ('Paroisse Notre Dame du Sacré-Cœur / Wonyomé', 'Wonyomé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Notre Dame sous la Croix / Agbalépédogan (SVD)', 'Agbalépédogan', 'Lomé-Ouest 1 (Klikamé)'),
    ('Paroisse Sacré-Cœur / Abobo', 'Abobo', 'Nord-Est 3 (Abobo)'),
    ('Paroisse Sacré-Cœur / Adangbé', 'Adangbé', 'Nord-Est 1 (Tsévié)'),
    ('Paroisse Sacré-Cœur / Kévé', 'Kévé', 'Nord-Ouest (Assahoun)'),
    ('Paroisse Sacré-Cœur de Jésus / Klémé', 'Klémé', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Paroisse Sacré-Cœur Junior / Tokoin-Est', 'Tokoin-Est', 'Lomé-Nord 2 (Tokoin)'),
    ('Paroisse Saint Antoine de Padoue / Adakpamé', 'Adakpamé', 'Lomé-Est 1 (Bè)'),
    ('Paroisse Saint Antoine de Padoue / Assikor', 'Assikor', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Paroisse Saint Antoine de Padoue / Gapé-Centre', 'Gapé-Centre', 'Nord-Est 2 (Agbélouvé)'),
    ('Paroisse Saint Antoine de Padoue / Hanoukopé (OFM)', 'Hanoukopé', 'Lomé-Centre'),
    ('Paroisse Saint Augustin / Amutivé', 'Amutivé', 'Lomé-Centre'),
    ('Paroisse Saint Benoît / Akodéssewa (SDB)', 'Akodéssewa', 'Lomé-Est 1 (Bè)'),
    ('Paroisse Saint Boniface / Kovié', 'Kovié', 'Nord-Ouest (Assahoun)'),
    ('Paroisse Saint Dominique Savio / Anfamé', 'Anfamé', 'Lomé-Est 1 (Bè)'),
    ('Paroisse Saint Esprit / Atitoé-Démé', 'Atitoé-Démé', 'Nord-Est 1 (Tsévié)'),
    ('Paroisse Saint Esprit / Djagblé', 'Djagblé', 'Nord-Est 3 (Abobo)'),
    ('Paroisse Saint Esprit / Totsi', 'Totsi', 'Lomé-Ouest 1 (Klikamé)'),
    ('Paroisse Saint François d''Assise / Madzikpéto', 'Madzikpéto', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Paroisse Saint Ignace / Logopé', 'Logopé', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Saint Jean Apôtre / Tsévié', 'Tsévié', 'Nord-Est 1 (Tsévié)'),
    ('Paroisse Saint Jean Baptiste / Hédzranawoé-Dzia', 'Hédzranawoé-Dzia', 'Lomé-Nord 1 (Hédzranawoé)'),
    ('Paroisse Saint Jean-Baptiste / Yokoé', 'Yokoé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Saint Jean-Bosco / Kangnikopé', 'Kangnikopé', 'Lomé-Est 2 (Baguida)'),
    ('Paroisse Saint Joseph / Akato (MCCJ)', 'Akato', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Saint Joseph / Avépozo', 'Avépozo', 'Lomé-Est 2 (Baguida)'),
    ('Paroisse Saint Joseph / Gbamakopé', 'Gbamakopé', 'Nord-Est 3 (Abobo)'),
    ('Paroisse Saint Joseph / Gbatopé', 'Gbatopé', 'Nord-Est 1 (Tsévié)'),
    ('Paroisse Saint Joseph / Kovié-Sévéxo-Dzémékè', 'Kovié-Sévéxo-Dzémékè', 'Nord-Ouest (Assahoun)'),
    ('Paroisse Saint Joseph / Kpomé-Akadzamé', 'Kpomé-Akadzamé', 'Nord-Est 3 (Abobo)'),
    ('Paroisse Saint Joseph / Togblékopé', 'Togblékopé', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Saint Jude Thaddée / Badja', 'Badja', 'Nord-Ouest (Assahoun)'),
    ('Paroisse Saint Kisito / Tokoin-Doumassessé', 'Tokoin-Doumassessé', 'Lomé-Nord 2 (Tokoin)'),
    ('Paroisse Saint Michel Archange / Davié (Eudistes)', 'Davié', 'Nord-Est 1 (Tsévié)'),
    ('Paroisse Saint Michel Archange / Mission Tové', 'Mission Tové', 'Nord-Ouest (Assahoun)'),
    ('Paroisse Saint Michel Archange / Tokoin-Casablanca', 'Tokoin-Casablanca', 'Lomé-Nord 2 (Tokoin)'),
    ('Paroisse Saint Paul d''Aflao / Avenou', 'Avenou', 'Lomé-Ouest 1 (Klikamé)'),
    ('Paroisse Saint Pierre Apôtre / Bassadji', 'Bassadji', 'Lomé-Centre'),
    ('Paroisse Saint Raphaël / Game Seva', 'Game Seva', 'Nord-Est 2 (Agbélouvé)'),
    ('Paroisse Sainte Croix / Sanguéra', 'Sanguéra', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Paroisse Sainte Élisabeth de Hongrie / Bolumodzi', 'Bolumodzi', 'Nord-Est 1 (Tsévié)'),
    ('Paroisse Sainte Famille / Agbélouvé', 'Agbélouvé', 'Nord-Est 2 (Agbélouvé)'),
    ('Paroisse Sainte Famille / Attiégou I', 'Attiégou I', 'Lomé-Nord 1 (Hédzranawoé)'),
    ('Paroisse Sainte Famille de Nazareth / Dangbésito', 'Dangbésito', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Paroisse Sainte Joséphine Bakhita / Sogbossito (Don Orione)', 'Sogbossito', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Sainte Lucie / Baguida', 'Baguida', 'Lomé-Est 2 (Baguida)'),
    ('Paroisse Sainte Madeleine de Canossa / Kové', 'Kové', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Paroisse Sainte Maria Goretti / Bè-Kpota', 'Bè-Kpota', 'Lomé-Est 1 (Bè)'),
    ('Paroisse Sainte Rita / Tokoin-Wuiti', 'Tokoin-Wuiti', 'Lomé-Nord 2 (Tokoin)'),
    ('Paroisse Sainte Rita / Zossimé', 'Zossimé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Sainte Thérèse de l''Enfant-Jésus / Kégué', 'Kégué', 'Lomé-Nord 1 (Hédzranawoé)'),
    ('Paroisse Saints Martyrs de l''Uganda / Have-Dumé', 'Have-Dumé', 'Nord-Est 3 (Abobo)'),
    ('Paroisse Saints Martyrs de l''Uganda / Tokoin', 'Tokoin', 'Lomé-Nord 2 (Tokoin)'),
    ('Paroisse Saints Pierre et Paul / Kagomé', 'Kagomé', 'Lomé-Est 2 (Baguida)'),
    ('Paroisse Saints Pierre et Paul / Noépé', 'Noépé', 'Nord-Ouest (Assahoun)'),
    ('Paroisse Sancta Maria Regina Pacis / Apédokoé', 'Apédokoé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Paroisse Ste Thérèse / Adamavo (SMA)', 'Adamavo', 'Lomé-Est 2 (Baguida)'),
    ('Paroisse Ste Thérèse / Aveta-Lowoé', 'Aveta-Lowoé', 'Nord-Est 3 (Abobo)'),
    ('Paroisse Ste Thérèse / Zopomahé', 'Zopomahé', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Paroisse Universitaire Saint Jean Apôtre (CSJ)', 'Tokoin', 'Lomé-Nord 2 (Tokoin)'),
    ('Quasi-paroisse Christ-Roi', 'Assahoun', 'Nord-Ouest (Assahoun)'),
    ('Quasi-paroisse Christ-Roi / Apessito', 'Apessito', 'Nord-Ouest (Assahoun)'),
    ('Quasi-paroisse Christ-Roi / Dalavé', 'Dalavé', 'Nord-Est 1 (Tsévié)'),
    ('Quasi-paroisse Notre Dame de l''Assomption / Gamélili', 'Gamélili', 'Nord-Est 2 (Agbélouvé)'),
    ('Quasi-paroisse Notre Dame de l''Assomption / Lom-Nava', 'Lom-Nava', 'Lomé-Est 2 (Baguida)'),
    ('Quasi-paroisse Notre Dame de l''Espérance / Afiadényigban (Franciscains)', 'Afiadényigban', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Quasi-paroisse Notre Dame de la Trinité / Afanoukopé (SMA)', 'Afanoukopé', 'Lomé-Est 2 (Baguida)'),
    ('Quasi-paroisse Notre Dame du Rosaire / Agotimé', 'Agotimé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Quasi-paroisse Notre Dame du Rosaire / Klobatémé', 'Klobatémé', 'Nord-Est 3 (Abobo)'),
    ('Quasi-paroisse Saint Arnold Janssen / Fidokpui Sivédomé (SVD)', 'Fidokpui Sivédomé', 'Lomé-Ouest 2 (Agoè-Nyivé)'),
    ('Quasi-paroisse Saint Augustin / Atti-Atovou', 'Atti-Atovou', 'Nord-Ouest (Assahoun)'),
    ('Quasi-paroisse Saint Christophe / Abolavé', 'Abolavé', 'Nord-Est 3 (Abobo)'),
    ('Quasi-paroisse Saint Daniel Comboni / Avédji-Anyigbé-Soviépé (MCCJ)', 'Avédji-Anyigbé-Soviépé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Quasi-paroisse Saint Esprit / Balissimé', 'Balissimé', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Quasi-paroisse Saint Esprit / Tovégan', 'Tovégan', 'Nord-Ouest (Assahoun)'),
    ('Quasi-paroisse Saint Juan Diego / Klokpoé', 'Klokpoé', 'Nord-Est 2 (Agbélouvé)'),
    ('Quasi-paroisse Saint Michel Archange', 'Assahoun', 'Nord-Ouest (Assahoun)'),
    ('Quasi-paroisse Saint Michel Archange / Dévégo', 'Dévégo', 'Lomé-Est 2 (Baguida)'),
    ('Quasi-paroisse Saint Michel Archange / Klémé Agokpanou', 'Klémé Agokpanou', 'Lomé-Ouest 3 (Adidogomé)'),
    ('Quasi-paroisse Saint Michel Archange / Koudassi', 'Koudassi', 'Nord-Ouest (Assahoun)'),
    ('Quasi-paroisse Sainte Thérèse / Akepé', 'Akepé', 'Nord-Ouest (Assahoun)'),
    ('Quasi-paroisse Sainte Thérèse d''Avila / Gati', 'Gati', 'Nord-Est 1 (Tsévié)'),
    ('Quasi-paroisse Sainte Thérèse d''Avila / Kognito (Carmes)', 'Kognito', 'Lomé-Ouest 4 (Sanguéra)'),
    ('Quasi-paroisse Sainte Thérèse de l''Enfant Jésus et de la Sainte Face', 'Assahoun', 'Nord-Ouest (Assahoun)'),
    ('Quasi-paroisse Saints Pierre et Paul / Agbodzékpo', 'Agbodzékpo', 'Nord-Est 2 (Agbélouvé)'),
    ('Quasi-paroisse Virgo Potens / Logogomé', 'Logogomé', 'Lomé-Ouest 3 (Adidogomé)')
) AS src(nom, adresse, doyenne)
LEFT JOIN doyenne dy
       ON lower(btrim(dy.nom)) = lower(btrim(src.doyenne))
      AND dy.status_del = FALSE
ON CONFLICT DO NOTHING;
