export const PRIMARY_REQUEST_TYPES = ['EUCHARISTIE', 'SACRAMENTAL', 'SACREMENT'];
export const PAYMENT_TYPES = ['TMONEY', 'FLOOZ', 'ESPECES', 'CARTE'];
export const WEEK_DAYS = ['LUNDI', 'MARDI', 'MERCREDI', 'JEUDI', 'VENDREDI', 'SAMEDI', 'DIMANCHE'];
