export const REQUEST_STATUSES = ['EN_ATTENTE', 'VALIDEE', 'REJETEE', 'TRAITEE'];
export const PAYMENT_STATUSES = ['EN_ATTENTE', 'PAYE', 'ECHEC', 'A_VERIFIER'];
export const VALIDATION_STATUSES = ['EN_ATTENTE', 'VALIDEE', 'REJETEE'];
